
local MemeStrings = {
	" sigma",
	" DECOMPILED BY Proohio DECOMPILER"
}

local Strings = {
	SUCCESS = "-- DECOMPILED BY Proohio DECOMPILER\n%s",
	TIMEOUT = "-- DECOMPILER GG",
	COMPILATION_FAILURE = "-- SCRIPT FAILED TO COMPILE, ERROR:\n%s",
	UNSUPPORTED_LBC_VERSION = "-- PASSED BYTECODE IS TOO OLD AND IS NOT SUPPORTED",
	USED_GLOBALS = "-- USED GLOBALS: %s.\n",
	DECOMPILER_REMARK = "-- DECOMPILER REMARK: %s\n"
}

return Strings
